import { sequelize } from "./src/db";
import app from "./src/app";
import { Job } from "./src/models/Job";
import { User } from "./src/models/User";

enum GenderType {
  Male = "masc",
  Female = "fem",
  Other = "otro",
}

enum RoleType {
  Admin = "admin",
  Employee = "empleado",
  Manager = "gerente",
}

sequelize
  .sync({ force: true, logging: false })
  .then(() => {
    console.log("base de datos conectada! :D");
    app.listen(3001, function () {
      console.log("App is listening on port 3001!");
    });
  })
  .then(async () => {
    await Job.bulkCreate([
      { id: "13-001", name: "Director D.E.M.E.S." },
      { id: "13-002", name: "Director D.N.I.P.y P" },
      { id: "13-003", name: "Asesor Técnico" },
      { id: "13-004", name: "Director D.I.I.E." },
      { id: "13-005", name: "Director D.I.P.E." },
      { id: "13-006", name: "Director D.A.E.I." },
      { id: "13-007", name: "Director D.E.A" },
      { id: "13-009", name: "Director D.E.F." },
      { id: "13-010", name: "Subdirector D.I.I.E." },
      { id: "13-011", name: "Subdirector D.E.M.E.S." },
      { id: "13-012", name: "Subdirector Perfecc. Educativo" },
      { id: "13-013", name: "Subdirector D.N.I.P.y P." },
      { id: "13-014", name: "Subdirector D.I.P.E." },
      { id: "13-015", name: "Inspector Gral. D.N.I.P. y P." },
      { id: "13-016", name: "Subdirector D.A.E.I." },
      { id: "13-017", name: "Subdirector D.E.F." },
      { id: "13-018", name: "Subdirector D.E.A." },
      { id: "13-019", name: "Inspector Gral.D.E.M.E.S." },
      { id: "13-020", name: "Inspector Gral. De Adultos" },
      { id: "13-021", name: "Inspector Gral. D.I.P.E." },
      { id: "13-023", name: "Inspector Gral. D.E.F." },
      { id: "13-024", name: "Subinspector Gral. D.E.M.E.S." },
      { id: "13-025", name: "Subinspector Gral. D.E.F." },
      { id: "13-030", name: "Subinspector Gral. D.N.I.P. y P." },
      { id: "13-035", name: "Inspector Gral. Instituto del Menor" },
      { id: "13-040", name: "Inspector D.E.M.E.S." },
      { id: "13-041", name: "Inspector de Jovenes y Adultos" },
      { id: "13-045", name: "Inspector D.E.F." },
      { id: "13-050", name: "Inspector Educación Complem." },
      { id: "13-055", name: "Inspector Instituto del Menor" },
      { id: "13-060", name: "Jefe Departamento Nutrición" },
      { id: "13-065", name: "Inspector D.N.I.P.y P." },
      { id: "13-070", name: "Supervisor Enseñanza Religiosa" },
      { id: "13-080", name: "Jefe Departamento Planeamiento" },
      { id: "13-085", name: "Jefe Departamento Planeamiento" },
      { id: "13-090", name: "Analista Mayor Planeamiento" },
      { id: "13-095", name: "Analista Principal Planeamiento" },
      { id: "13-100", name: "Presidente Junta Clas. Primaria" },
      { id: "13-101", name: "Vocal Junta Clas. Primaria" },
      { id: "13-102", name: "Miembro Vocal de Junta D.E.M.E.S." },
      { id: "13-105", name: "Director de 1ª Enseñanza Superior" },
      { id: "13-110", name: "Director de 2ª Enseñanza Superior" },
      { id: "13-115", name: "Vicedirector de Enseñ. Superior" },
      { id: "13-120", name: "Regente de Enseñ. Superior" },
      { id: "13-140", name: "Director de 1ª Ens. Media J. Comp" },
      { id: "13-143", name: "Director de 2ª Ens. Media J. Comp" },
      { id: "13-145", name: "Director de 3ª Ens. Media J. Comp" },
      { id: "13-150", name: "Director de 1ª Ens. Media" },
      { id: "13-153", name: "Director de 1ª Ens. Especial" },
      { id: "13-155", name: "Director de 2ª Ens. Media" },
      { id: "13-157", name: "Director de 2ª Ens. Especial" },
      { id: "13-160", name: "Director de 3ª Ens. Media" },
      { id: "13-163", name: "Director de 3ª Ens. Especial" },
      { id: "13-164", name: "Vicedirector Ens. Media J. Compl." },
      { id: "13-165", name: "Vicedirector de 1ª  Ens. Media" },
      { id: "13-167", name: "Vicedirector de 1ª  Ens. Especial" },
      { id: "13-170", name: "Vicedirector de 2ª  Ens. Media" },
      { id: "13-173", name: "Vicedirector de 2ª  Ens. Especial" },
      { id: "13-175", name: "Vicedirector de 3ª  Ens. Media" },
      { id: "13-178", name: "Vicedirector de 3ª  Ens. Especial" },
      { id: "13-179", name: "Asesor Pedagógico Proyecto 13" },
      { id: "13-180", name: "Regente de 1ª Ens. Media" },
      { id: "13-181", name: "Regente de 1ª Ens. Media J. Com." },
      { id: "13-183", name: "Regente de 1ª Ens. Primaria" },
      { id: "13-184", name: "Regente de 2ª Ens. Media J. Com." },
      { id: "13-185", name: "Regente Educación Artística" },
      { id: "13-186", name: "Regente de 3ª Ens. Media J. Com." },
      { id: "13-187", name: "Director de Coro" },
      { id: "13-188", name: "Director de Coro Jornada Reducida" },
      { id: "13-189", name: "Director de Orquesta de Ctro.Educ" },
      { id: "13-190", name: "Jefe Gabinete Psicopedagógico" },
      { id: "13-195", name: "Regente de 2ª Ens. Media" },
      { id: "13-196", name: "Regente de 3ª Ens. Media" },
      { id: "13-197", name: "Regente de 2ª Ens. Primaria" },
      { id: "13-200", name: "Subregente de 1ª Ens. Media" },
      { id: "13-203", name: "Subregente de 1ª Ens. Primaria" },
      { id: "13-205", name: "Jefe Departamento Didáctico" },
      { id: "13-210", name: "Coordinador Curso Ens. Superior" },
      { id: "13-215", name: "Coordinador Curso Ens. Media" },
      { id: "13-250", name: "Director Cantina Base" },
      { id: "13-255", name: "Director de 1ª Ens. Primaria" },
      { id: "13-255", name: "Director de 1ª Ens. Primaria (Jardin Inf)" },
      { id: "13-256", name: "Director de 1ª Ens. Prim.T. P. P." },
      { id: "13-260", name: "Director de 2ª Ens. Primaria" },
      { id: "13-260", name: "Director de 2ª Ens. Primaria (Jardin Inf)" },
      { id: "13-265", name: "Director de 3ª Ens. Primaria" },
      { id: "13-265", name: "Director de 3ª Ens. Primaria (Jardin Inf)" },
      { id: "13-270", name: "Vicedirector Ens. Primaria" },
      { id: "13-290", name: "Regente Ctro. Educ. Complemen." },
      { id: "13-293", name: "Dir. 1ª Ctro. Dep. Educ. Física" },
      { id: "13-294", name: "Dir. 2ª Ctro. Dep. Educ. Física" },
      { id: "13-295", name: "Dir. 3ª Ctro. Dep. Educ. Física" },
      { id: "13-298", name: "Coordinador Reg. Educ. Física" },
      { id: "13-300", name: "Vicedirec. de 1ª Ctro.Dep.Ed.F." },
      { id: "13-301", name: "Vicedirec. de 2ª Ctro.Dep.Ed.F." },
      { id: "13-302", name: "Vicedirec. de 3ª Ctro.Dep.Ed.F." },
      { id: "13-305", name: "Secretario (Enseñanza Superior)" },
      { id: "13-307", name: "Prosecr. Docente Ens. Superior" },
      { id: "13-310", name: "Secretario Doc. de 1ª Ens. Media" },
      { id: "13-315", name: "Secretario Doc. de 2ª Ens. Media" },
      { id: "13-320", name: "Secretario Doc. de 3ª Ens. Media" },
      { id: "13-325", name: "Prosecr. Doc. de 1ª Ens. Media" },
      { id: "13-330", name: "Prosecr. Doc. de 2ª Ens. Media" },
      { id: "13-335", name: "Prosecr. Doc. de 3ª Ens. Media" },
      { id: "13-340", name: "Secretario Docente Ens. Especial" },
      { id: "13-345", name: "Prosecr. Docente Ens. Especial" },
      { id: "13-350", name: "Secr. Doc. de 1ª Ens. Primaria" },
      { id: "13-355", name: "Secr. Doc. de 2ª Ens. Primaria" },
      { id: "13-360", name: "Secr. Doc. de 3ª Ens. Primaria" },
      { id: "13-365", name: "Secr. Doc. de 4ª Ens. Primaria" },
      { id: "13-370", name: "Secr. Doc. de 5ª Ens. Primaria" },
      { id: "13-420", name: "Jefe de Internado" },
      { id: "13-425", name: "Jefe Enseñanza Practica de 1ª" },
      { id: "13-430", name: "Jefe Enseñanza Practica de 2ª" },
      { id: "13-435", name: "Jefe Enseñanza Practica de 3ª" },
      { id: "13-436", name: "Instructor Jor. Compl. Agr." },
      { id: "13-437", name: "Jefe Sección Jorn. Completa" },
      { id: "13-438", name: "Instructor Enfermería" },
      { id: "13-440", name: "Encar.Secc.Gab.Psicop.(Med. y Sup.)" },
      { id: "13-443", name: "Encar.Secc.Gab.Psicop.(Especial)" },
      { id: "13-444", name: "Jefe de Gabinete Psicoped. (Primar.)" },
      { id: "13-445", name: "Ayudante de Gab. Psic. Ens. M y Sup" },
      { id: "13-447", name: "Ayudante de Gab. Psic. Ens. Esp." },
      { id: "13-448", name: "Ayudante de Gab. Psic. Ens. Prim." },
      { id: "13-450", name: "Maestro de Grupo Escolar" },
      { id: "13-455", name: "Maestro de Grado Ens. Especial" },
      { id: "13-457", name: "Reeducador Especial" },
      { id: "13-460", name: "Encargado de Taller" },
      { id: "13-463", name: "Jefe de Trabajos Prácticos" },
      { id: "13-464", name: "Jefe de Laboratorio" },
      { id: "13-465", name: "Jefe de Gabinete Contabilidad" },
      { id: "13-466", name: "Jefe de Dpto. Educ. Física" },
      { id: "13-470", name: "Prof. Ctro. Depor. Educ. Física" },
      { id: "13-472", name: "Jefe de Ens. Pract. Ens. Especial" },
      { id: "13-473", name: "Jefe de Sección Ens. Practica" },
      { id: "13-475", name: "Maestra de Grado Ens. Primaria" },
      { id: "13-476", name: "Maestro Grado Pasividad Perman." },
      { id: "13-477", name: "Maestro de D. E. A." },
      { id: "13-480", name: "Maestro de Jardín de Infantes" },
      { id: "13-484", name: "Maestro Ens. Practica Ens. Esp." },
      { id: "13-485", name: "Maestro Enseñanza Practica" },
      { id: "13-486", name: "Maestro de Grado Artístico" },
      { id: "13-487", name: "Maestro de Grado Artístico Jorn. Red." },
      { id: "13-488", name: "Maestro de Grado de Adultos" },
      { id: "13-490", name: "Maestro Cultura General" },
      { id: "13-495", name: "Bibliotecario Jefe" },
      { id: "13-500", name: "Bibliotecario" },
      { id: "13-505", name: "Ayudante Técnico" },
      { id: "13-507", name: "Jefe de Preceptores J. Completa" },
      { id: "13-510", name: "Jefe de Preceptores" },
      { id: "13-512", name: "Subjefe de Preceptores de 1ª" },
      { id: "13-514", name: "Maestro Cultura Rural Dom" },
      { id: "13-515", name: "Maestro Materia Especial" },
      { id: "13-515", name: "Maestro Mat. Esp. - Ex. Cons. Menor" },
      { id: "13-517", name: "Maestro Esp Artística" },
      { id: "13-520", name: "Preceptor" },
      { id: "13-520", name: "Preceptor Escuela de Mod Especial" },
      { id: "13-700", name: "Director de 1ª Inst. del Menor" },
      { id: "13-705", name: "Director de 2ª Inst. del Menor" },
      { id: "13-710", name: "Director de 3ª Inst. del Menor" },
      { id: "13-715", name: "Vicedir de 1ª Instit. del Menor" },
      { id: "13-720", name: "Vicedir de 2ª Instit. del Menor" },
      { id: "13-725", name: "Vicedir de 3ª Instit. del Menor" },
      { id: "13-730", name: "Regente de Instituto del Menor" },
      { id: "13-732", name: "Secr. Doc. de 1ª Inst. Menor" },
      { id: "13-733", name: "Secr. Doc. de 2ª Inst. Menor" },
      { id: "13-735", name: "Maestro de Inst. de Menores" },
      { id: "13-740", name: "Dir. de 1ª Jornada Completa" },
      { id: "13-743", name: "Dir. de 2ª Jornada Completa" },
      { id: "13-745", name: "Dir. de 3ª Jornada Completa" },
      { id: "13-747", name: "Vicedirector Jornada Completa" },
      { id: "13-748", name: "Maestro Grado Jorn. Completa" },
      { id: "13-749", name: "Maestro Ram. Esp. Jor. Compl." },
      { id: "13-750", name: "Director Escuela Hogar" },
      { id: "13-760", name: "Director 2ª Anexo Albergue" },
      { id: "13-765", name: "Director 3ª Anexo Albergue" },
      { id: "13-767", name: "Maestro Anexo Albergue" },
      { id: "13-769", name: "Maestro Ram. Esp. An. Alber." },
      { id: "13-770", name: "Vicedir. Esc. Hogar Te." },
      { id: "13-775", name: "Secretario Téc. Esc. Hogar" },
      { id: "13-780", name: "Jefe Serv. Soc. Esc. Hogar" },
      { id: "13-785", name: "Visitador Higiene Social" },
      { id: "13-795", name: "Maestro Grado Esc. Hogar" },
      { id: "13-797", name: "Preceptor Jor Compl, Esc Hogar, An Alb" },
      { id: "13-800", name: "Mtro. Mat. Esp. Esc. Hogar" },
      { id: "13-900", name: "Hora Cátedra Enseñanza Superior 1 hs" },
      { id: "13-900", name: "Hora Cátedra Enseñanza Superior 2 hs" },
    ]);
    await User.bulkCreate([
      {
        cuil: "230422752819",
        name: "Carlos Salvador",
        lastName: "Bilardo",
        password: "123456789",
        address: "Kiricocho 13",
        phoneNumber: "01113131313",
        emailAddress: "elDoctor@gmail.com",
        seniorityDate: "2022-04-29 04:50:12.390 +00:00",
        gender: GenderType.Male,
        role: RoleType.Admin,
      },
      {
        cuil: "200422352811",
        name: "Pruebita",
        lastName: "Pruebon",
        password: "unacontrase",
        address: "sí tiene 8",
        phoneNumber: "01113131313",
        emailAddress: "elDoctor@gmail.com",
        seniorityDate: "2022-04-29 04:50:12.390 +00:00",
        gender: GenderType.Male,
        role: RoleType.Admin,
      },
    ]);
  })
  .catch((err) => console.error(err));
